spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:callbus
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  config: classpath:logback-spring.xml
#  file:
#    name: info.log
#    path: logs

